---
- name: Connect to python script
  hosts: AOTLXPPTHA00002
  user: icm
  tasks:
   ## PRUEBA PS ##
    - name: Ejecucion proceso de automatización
      script: /icm/auto_ps/Automatizacion_INC_PS.py
      remote_src: yes
      args:
        executable: /usr/bin/python
