---
- name: Connect to python script
  hosts: AOTLXPPTHA00002
  user: icm
  tasks:
   ## PRUEBA PS ##
    - name: Execute a script
      script: /icm/auto_ps/Automatizacion_INC_PS.py
      args:
        executable: /usr/bin/python
