---
- name: Connect to python script
  hosts: AOTLXPPTHA00002
  user: icm
  vars:
  tasks:
   ## PRUEBA PS ##
    - name: Ejecucion proceso de automatización
      shell: python /icm/auto_ps/Automatizacion_INC_PS.py
      args:
        executable: /usr/bin/python
