---
- name: Connect to python script
  hosts: Monitor
  user: neos
  vars:
  tasks:
   ## PRUEBA PS ##
    - name: Execute a script
      shell: |
                                ./incidenciasPS.sh
      args:
        executable: /bin/bash
        chdir: /home/neos/DMN/awx

